#!/bin/sh
#
# Coldplug modules....
#

case "$1" in
  start)
	echo "Coldplug modules..."
	# coldplug modules
	find /sys/ -name modalias -print0 | xargs -0 sort -u -z | xargs -0 -n 1 modprobe -q
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
